### PR TITLE
Implement Singleton Overlay and Multiple Notification

### PR DESCRIPTION
**Pull request by manolo**
Connected to #5

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-notification/7)

### CODE REVIEW

**Comment by manolo** [comment]
Review status: 8 of 12 files reviewed at latest revision, 4 unresolved discussions.

---

*[vaadin-notification.html, line 269 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-notification/7#-KyWWK54vagyGJqxVsMR:-KyZaEgvK3SGRcQuh8Xb:b-896fix) ([raw file](https://github.com/vaadin/vaadin-notification/blob/b73a482037bd595bd5feaa70f3de65555aaf9297/vaadin-notification.html#L269)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

nit: trailing comma
</blockquote></details>

Done.

---

*[vaadin-notification.html, line 338 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-notification/7#-KyWWt-VedjCLVNO0s95:-KyZfwnAwX0csX5BZHaO:b-896fix) ([raw file](https://github.com/vaadin/vaadin-notification/blob/b73a482037bd595bd5feaa70f3de65555aaf9297/vaadin-notification.html#L338)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

Consider adding some check here to prevent errors. E. g. when setting `verticalAlign` to `center` by mistake (instead of `middle`) and then calling `open`, I would expect some warning in the console but I get this error instead:
```
Uncaught TypeError: Cannot read property 'appendChild' of undefined
    at HTMLElement._appendNotificationCard (vaadin-notification.html:338)
```
</blockquote></details>

Done.

---

*[demo/notification-advanced-demos.html, line 43 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-notification/7#-KyWX_RdZ-QxvFHDfY9C:-KyZaJyyQi-60jo-_Owh:b-896fix) ([raw file](https://github.com/vaadin/vaadin-notification/blob/b73a482037bd595bd5feaa70f3de65555aaf9297/demo/notification-advanced-demos.html#L43)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

 This line looks inconsistent to me. I would expect to see the actual value here, which is `middle`. 
</blockquote></details>

Done.

---

*[test/multiple-notification-test.html, line 139 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-notification/7#-KyWZ6UWuFtAG7BX7bQX:-KyZaAn6r-g4jALIyvpY:b-896fix) ([raw file](https://github.com/vaadin/vaadin-notification/blob/b73a482037bd595bd5feaa70f3de65555aaf9297/test/multiple-notification-test.html#L139)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

nit: remove this line
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-notification/7)*

**Comment by tomivirkki** [comment]
*[vaadin-notification.html, line 98 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-notification/7#-Ky_29lHy-MtkrcDLa42:-Ky_29lHy-MtkrcDLa43:b-pvg7uu) ([raw file](https://github.com/vaadin/vaadin-notification/blob/60a4e4e64abbdc815137ecb056e198acd1853ed5/vaadin-notification.html#L98)):*
> ```HTML
>     <div part="overlay" id="overlay">
>       <div part="content" id="content">
>         <div part="top-stretch"></div>
> ```

Is there a reason to define the regions as parts? Are they needed in styling?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-notification/7)*

**Comment by manolo** [comment]
Review status: 8 of 12 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[vaadin-notification.html, line 98 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-notification/7#-Ky_29lHy-MtkrcDLa42:-Ky_ButbbmBz9UFSBxAO:b47jnnc) ([raw file](https://github.com/vaadin/vaadin-notification/blob/60a4e4e64abbdc815137ecb056e198acd1853ed5/vaadin-notification.html#L98)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Is there a reason to define the regions as parts? Are they needed in styling?
</blockquote></details>

Well, the theme developer might want to adjust certain parameters like where the notification is aligned, etc. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-notification/7)*

**Comment by tomivirkki** [comment]
*[vaadin-notification.html, line 98 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-notification/7#-Ky_29lHy-MtkrcDLa42:-Ky_LrnV8MnB1_p_C3aS:b5f86d5) ([raw file](https://github.com/vaadin/vaadin-notification/blob/60a4e4e64abbdc815137ecb056e198acd1853ed5/vaadin-notification.html#L98)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

Well, the theme developer might want to adjust certain parameters like where the notification is aligned, etc. 
</blockquote></details>

Is this necessary @jouni? Kind of feels like overkill to expose the regions. If we expose them now as public API, we can't modify them later.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-notification/7)*

**Comment by web-padawan** [comment]
Reviewed 3 of 4 files at r2, 1 of 2 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks broke.

---

*[vaadin-notification.html, line 104 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-notification/7#-KybD3Oq5U-_YV89NyMN:-KybD3Oq5U-_YV89NyMO:bvp8fmq) ([raw file](https://github.com/vaadin/vaadin-notification/blob/be84ee99437bed9bc5d83ab21efb2548ed930ebb/vaadin-notification.html#L104)):*
> ```HTML
>       }
> 
>       @media screen and (max-width: 420px) {
> ```

The `screen` media type could be safely omitted. Here is the good reading related: https://stackoverflow.com/a/28444066

---

*[vaadin-notification.html, line 112 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-notification/7#-KybB_Cc8_yO7uTNUwvZ:-KybB_Cc8_yO7uTNUwv_:b81xfdw) ([raw file](https://github.com/vaadin/vaadin-notification/blob/be84ee99437bed9bc5d83ab21efb2548ed930ebb/vaadin-notification.html#L112)):*
> ```HTML
>         [part="bottom"] {
>           flex-direction: column;
>           flex: initial;
> ```

AFAIK, `initial` is not supported by IE11: https://caniuse.com/#feat=css-initial-value
I'd recommend using `auto` where possible, at least for `max-width` it works.

---

*[demo/notification-basic-demos.html, line 43 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-notification/7#-KybE1I-u3X5uiet5REJ:-KybE1I-u3X5uiet5REK:bsa8ar4) ([raw file](https://github.com/vaadin/vaadin-notification/blob/be84ee99437bed9bc5d83ab21efb2548ed930ebb/demo/notification-basic-demos.html#L43)):*
> ```HTML
>         <script>
>           window.showNotification = function() {
>             const template = window.document.createElement('template');
> ```

There is an inconsistency here: `window.document` vs `document` below. Is there any particular reason to use `window.document`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-notification/7)*

**Comment by manolo** [comment]
Review status: 11 of 13 files reviewed at latest revision, 4 unresolved discussions, some commit checks broke.

---

*[vaadin-notification.html, line 104 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-notification/7#-KybD3Oq5U-_YV89NyMN:-KybLkLhFkDspl4WBhNz:b-896fix) ([raw file](https://github.com/vaadin/vaadin-notification/blob/be84ee99437bed9bc5d83ab21efb2548ed930ebb/vaadin-notification.html#L104)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

The `screen` media type could be safely omitted. Here is the good reading related: https://stackoverflow.com/a/28444066
</blockquote></details>

Done.

---

*[vaadin-notification.html, line 112 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-notification/7#-KybB_Cc8_yO7uTNUwvZ:-KybLQt3ZymVhXQQtqCN:b-896fix) ([raw file](https://github.com/vaadin/vaadin-notification/blob/be84ee99437bed9bc5d83ab21efb2548ed930ebb/vaadin-notification.html#L112)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

AFAIK, `initial` is not supported by IE11: https://caniuse.com/#feat=css-initial-value
I'd recommend using `auto` where possible, at least for `max-width` it works.
</blockquote></details>

Done.

---

*[demo/notification-basic-demos.html, line 43 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-notification/7#-KybE1I-u3X5uiet5REJ:-KybHloMd8wJKpuH92Qr:b-v7o1xs) ([raw file](https://github.com/vaadin/vaadin-notification/blob/be84ee99437bed9bc5d83ab21efb2548ed930ebb/demo/notification-basic-demos.html#L43)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

There is an inconsistency here: `window.document` vs `document` below. Is there any particular reason to use `window.document`?
</blockquote></details>

it's not needed here, only the  window.showNotification. Otherwise in scripts wrapped with the window.addDemoReadyListener they are needed 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-notification/7)*

**Comment by web-padawan** [comment]
Reviewed 1 of 2 files at r5.
Review status: 12 of 13 files reviewed at latest revision, 2 unresolved discussions.

---

*[vaadin-notification.html, line 112 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-notification/7#-KybB_Cc8_yO7uTNUwvZ:-KybQ_ZmerG6aloJCMFs:b-bgjv5t) ([raw file](https://github.com/vaadin/vaadin-notification/blob/be84ee99437bed9bc5d83ab21efb2548ed930ebb/vaadin-notification.html#L112)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I wonder if the `inherit` is a proper solution, despite it does the trick. 
Using explicit values like `flex: 0 1 auto`, which is equivalent to `flex: initial`, is easier to understand. Personally, I would take a look at the spec were initial values are listed for each property.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-notification/7)*

**Comment by web-padawan** [comment]
Reviewed 1 of 2 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-notification/7)*

**Comment by tomivirkki** [comment]
Reviewed 7 of 12 files at r1, 3 of 4 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[vaadin-notification.html, line 98 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-notification/7#-Ky_29lHy-MtkrcDLa42:-Kyb52gciEnTXv-SDq1M:b-v6zjkb) ([raw file](https://github.com/vaadin/vaadin-notification/blob/60a4e4e64abbdc815137ecb056e198acd1853ed5/vaadin-notification.html#L98)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Is this necessary @jouni? Kind of feels like overkill to expose the regions. If we expose them now as public API, we can't modify them later.
</blockquote></details>

Well, they may be needed after all. We can revisit this during alpha period

---

*[vaadin-notification.html, line 166 at r5](https://reviewable.io:443/reviews/vaadin/vaadin-notification/7#-Kyejh-1cb-SJfRxMTHJ:-Kyejh-1cb-SJfRxMTHK:b-f4sd5h) ([raw file](https://github.com/vaadin/vaadin-notification/blob/dcb718cea770021aefa689b499f919b2b01dbaed/vaadin-notification.html#L166)):*
> ```HTML
>         width: 100%;
>         max-width: 250px;
>         font-size: 12px;
> ```

Why override font size in default theme?

---

*[vaadin-notification.html, line 169 at r5](https://reviewable.io:443/reviews/vaadin/vaadin-notification/7#-KyenzBfu1EVAygBNleN:-KyenzBfu1EVAygBNleO:bbkpoqr) ([raw file](https://github.com/vaadin/vaadin-notification/blob/dcb718cea770021aefa689b499f919b2b01dbaed/vaadin-notification.html#L169)):*
> ```HTML
>         background: lightgrey;
>         box-shadow: 0 2px 4px 0 rgba(0, 0, 0, 0.3);
>         max-height: 15em;
> ```

Does this need a max-height? Could be removed?

---

*[vaadin-notification.html, line 170 at r5](https://reviewable.io:443/reviews/vaadin/vaadin-notification/7#-Kyeo2XEpROczzx8xHdZ:-Kyeo2XEpROczzx8xHd_:b-yt9kfl) ([raw file](https://github.com/vaadin/vaadin-notification/blob/dcb718cea770021aefa689b499f919b2b01dbaed/vaadin-notification.html#L170)):*
> ```HTML
>         box-shadow: 0 2px 4px 0 rgba(0, 0, 0, 0.3);
>         max-height: 15em;
>       }
> ```

Add `pointer-events: auto;` to make the card accessible by default

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-notification/7)*

**Comment by tomivirkki** [comment]
*[vaadin-notification.html, line 170 at r5](https://reviewable.io:443/reviews/vaadin/vaadin-notification/7#-Kyeo2XEpROczzx8xHdZ:-Kyf4VN_rFAs_4CyGJmh:blkw5yd) ([raw file](https://github.com/vaadin/vaadin-notification/blob/dcb718cea770021aefa689b499f919b2b01dbaed/vaadin-notification.html#L170)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Add `pointer-events: auto;` to make the card accessible by default
</blockquote></details>

...not in the default theme though

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-notification/7)*

**Comment by manolo** [comment]
Review status: 12 of 13 files reviewed at latest revision, 4 unresolved discussions.

---

*[vaadin-notification.html, line 98 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-notification/7#-Ky_29lHy-MtkrcDLa42:-Kyg2DjsI2w_b-7LHyzi:bcfma5r) ([raw file](https://github.com/vaadin/vaadin-notification/blob/60a4e4e64abbdc815137ecb056e198acd1853ed5/vaadin-notification.html#L98)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Well, they may be needed after all. We can revisit this during alpha period
</blockquote></details>

Agree, that is easy to change

---

*[vaadin-notification.html, line 112 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-notification/7#-KybB_Cc8_yO7uTNUwvZ:-Kyg9UYvd7EpRz2rhg68:b-224y7g) ([raw file](https://github.com/vaadin/vaadin-notification/blob/be84ee99437bed9bc5d83ab21efb2548ed930ebb/vaadin-notification.html#L112)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

I wonder if the `inherit` is a proper solution, despite it does the trick. 
Using explicit values like `flex: 0 1 auto`, which is equivalent to `flex: initial`, is easier to understand. Personally, I would take a look at the spec were initial values are listed for each property.
</blockquote></details>

much better, Done

---

*[vaadin-notification.html, line 166 at r5](https://reviewable.io:443/reviews/vaadin/vaadin-notification/7#-Kyejh-1cb-SJfRxMTHJ:-Kyg-4vrRYHwxt_egLpX:b6g44si) ([raw file](https://github.com/vaadin/vaadin-notification/blob/dcb718cea770021aefa689b499f919b2b01dbaed/vaadin-notification.html#L166)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Why override font size in default theme?
</blockquote></details>

It was in the jsfiddle prototype, removed

---

*[vaadin-notification.html, line 169 at r5](https://reviewable.io:443/reviews/vaadin/vaadin-notification/7#-KyenzBfu1EVAygBNleN:-Kyg1nb7V-dOthMo32MH:bx6q1od) ([raw file](https://github.com/vaadin/vaadin-notification/blob/dcb718cea770021aefa689b499f919b2b01dbaed/vaadin-notification.html#L169)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Does this need a max-height? Could be removed?
</blockquote></details>

Also from the prototype. Removed

---

*[vaadin-notification.html, line 170 at r5](https://reviewable.io:443/reviews/vaadin/vaadin-notification/7#-Kyeo2XEpROczzx8xHdZ:-Kyg20GwdWMlLfHnhIg6:b-qu6n94) ([raw file](https://github.com/vaadin/vaadin-notification/blob/dcb718cea770021aefa689b499f919b2b01dbaed/vaadin-notification.html#L170)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

...not in the default theme though
</blockquote></details>

Good point. Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-notification/7)*

**Comment by tomivirkki** [comment]
:lgtm:

---

Reviewed 1 of 12 files at r1, 4 of 4 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-notification/7#-:-KyoYB_RfNCA9WMUyAbw:bnfp4nl)*

**Comment by web-padawan** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-notification/7#-:-KyoczZ7yoofkE_j83P4:bnfp4nl)*

**Comment by manolo** [comment]
Reviewed 1 of 1 files at r8.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-notification/7)*

**Pull request merged**
