### PR TITLE
Implement animations

### LINKED ISSUE #10: Make the cards animatable
Currently, the cards are directly removed from dom on close which makes them non-animatable.

When closing a card:
1. Mark it as closing with a state attribute and check if it has a CSS animation (for closing) defined
2. If not, remove from dom as currently
3. If yes, add an `animationend` listener for that animation and do the removal only once it triggers

### PR DESCRIPTION
**Pull request by manolo**
Fixes #10

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-notification/20)

### CODE REVIEW

**Comment by platosha** [comment]
The pr title and the branch name contain “fixture” instead of “feature”. Fine by me, just wanted to warn you of this.

---

Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---

*[test/animate-notification-test.html, line 52 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-notification/20#-KzOyGBIiH8eSQyyxT11:-KzOyGBIiH8eSQyyxT12:bj3zooa) ([raw file](https://github.com/vaadin/vaadin-notification/blob/837c5260708d7e1dab681626f14cd13bdef75670/test/animate-notification-test.html#L52)):*
> ```HTML
>         notifications = Array.from(fixture('notification'));
>         overlay = notifications[0]._overlay;
>         setTimeout(done);
> ```

Lots of magic timeout numbers in this suite, this is nasty.

Note that most of the tests run expectations after a timeout. It is probably possible to move the common initial timeout here to this beforeEach. After that you can unwrap the expectations from `setTimeout` in a few of tests.

In general, maybe use an explicit `Promise` instead of timeouts here? Consider something like this pseudo-code:

```javascript
// in notification close handler
if (animationIsDefined) {
  // a private prop with a Promise, which resolves after animation end
  this._closing = new Promise((resolve) =>
    this.addEventListener('animationend', () => {
      this._removeNotificationCard();
      resolve();
    }));
} else {
  // a prop is undefined if sync closing is used
  this._closing = undefined;
  this._removeNotificationCard();
}
```

Then in the tests you can express timing namely, instead of a magic timeout number:
```javascript
// should remove card from DOM
this._closing.then(() => {
  expect(notification.card.parentNode).to.be.null;
});
```

---

*[test/animate-notification-test.html, line 56 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-notification/20#-KzOxnQtePlZwyuPheJN:-KzOxnQtePlZwyuPheJO:btc30z8) ([raw file](https://github.com/vaadin/vaadin-notification/blob/837c5260708d7e1dab681626f14cd13bdef75670/test/animate-notification-test.html#L56)):*
> ```HTML
> 
>       describe('animation', () => {
>         it('should remove card inmediatly if not animation defined', done => {
> ```

typos, should say: `should remove card immediately if no animation defined`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-notification/20#-:-KzOwnak4hI-TRRSeNNN:b-lrbxsg)*

**Comment by web-padawan** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks broke.

---

*[vaadin-notification.html, line 415 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-notification/20#-KzSWK5F9wUNtOdWWrwg:-KzSWK5F9wUNtOdWWrwh:b-60kxzg) ([raw file](https://github.com/vaadin/vaadin-notification/blob/837c5260708d7e1dab681626f14cd13bdef75670/vaadin-notification.html#L415)):*
> ```HTML
>           this._card.setAttribute('closing', '');
>           if (!this._endHandler) {
>             const name = getComputedStyle(this._card).getPropertyValue('animation-name');
> ```

Should also test for ShadyCSS and use corresponding workaround:
```
ShadyCSS.getComputedStyleValue('animation-name');
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-notification/20)*

**Comment by web-padawan** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---

*[vaadin-notification.html, line 415 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-notification/20#-KzSWK5F9wUNtOdWWrwg:-KzSYiIzULEjY13CNa0O:b-8ykwed) ([raw file](https://github.com/vaadin/vaadin-notification/blob/837c5260708d7e1dab681626f14cd13bdef75670/vaadin-notification.html#L415)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

Should also test for ShadyCSS and use corresponding workaround:
```
ShadyCSS.getComputedStyleValue('animation-name');
```
</blockquote></details>

My mistake, that is not a CSS custom property, so please ignore.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-notification/20)*

**Comment by manolo** [comment]
Changed title of the PR

---

Review status: 3 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[test/animate-notification-test.html, line 52 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-notification/20#-KzOyGBIiH8eSQyyxT11:-KzTMgPOdAFtO_MI3Bmz:bufgr5s) ([raw file](https://github.com/vaadin/vaadin-notification/blob/837c5260708d7e1dab681626f14cd13bdef75670/test/animate-notification-test.html#L52)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

Lots of magic timeout numbers in this suite, this is nasty.

Note that most of the tests run expectations after a timeout. It is probably possible to move the common initial timeout here to this beforeEach. After that you can unwrap the expectations from `setTimeout` in a few of tests.

In general, maybe use an explicit `Promise` instead of timeouts here? Consider something like this pseudo-code:

```javascript
// in notification close handler
if (animationIsDefined) {
  // a private prop with a Promise, which resolves after animation end
  this._closing = new Promise((resolve) =>
    this.addEventListener('animationend', () => {
      this._removeNotificationCard();
      resolve();
    }));
} else {
  // a prop is undefined if sync closing is used
  this._closing = undefined;
  this._removeNotificationCard();
}
```

Then in the tests you can express timing namely, instead of a magic timeout number:
```javascript
// should remove card from DOM
this._closing.then(() => {
  expect(notification.card.parentNode).to.be.null;
});
```
</blockquote></details>

Changed the magic numbers.

About promisies, I don't want to create a new promise or add even listeners each time that the notification is used. 
Adding listener once works everytime instead

---

*[test/animate-notification-test.html, line 56 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-notification/20#-KzOxnQtePlZwyuPheJN:-KzTMzTj6rOE015Nx59f:b-896fix) ([raw file](https://github.com/vaadin/vaadin-notification/blob/837c5260708d7e1dab681626f14cd13bdef75670/test/animate-notification-test.html#L56)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

typos, should say: `should remove card immediately if no animation defined`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-notification/20#-:-KzTM_6kt37sjKaqv4wp:bxei741)*

**Comment by platosha** [comment]
Reviewed 2 of 4 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[test/animate-notification-test.html, line 56 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-notification/20#-KzOxnQtePlZwyuPheJN:-KzTtd0iusLQqVuFDgCT:b-vboj5) ([raw file](https://github.com/vaadin/vaadin-notification/blob/837c5260708d7e1dab681626f14cd13bdef75670/test/animate-notification-test.html#L56)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not done. :-(

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-notification/20)*

**Comment by YuriyVaadin** [comment]
Reviewed 2 of 4 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[test/animate-notification-test.html, line 56 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-notification/20#-KzOxnQtePlZwyuPheJN:-KzTvEXlnz8OrVFcyH4u:b-gpxmh1) ([raw file](https://github.com/vaadin/vaadin-notification/blob/837c5260708d7e1dab681626f14cd13bdef75670/test/animate-notification-test.html#L56)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

Not done. :-(
</blockquote></details>

Nit: `inmediatly` -> `immediately`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-notification/20)*

**Comment by YuriyVaadin** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-notification/20#-:-KzY6g5OxaQhWbqviSXU:bnfp4nl)*

**Comment by manolo** [comment]
Review status: 2 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[test/animate-notification-test.html, line 56 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-notification/20#-KzOxnQtePlZwyuPheJN:-KzY95p3H3Ism9Lv3adh:b-896fix) ([raw file](https://github.com/vaadin/vaadin-notification/blob/837c5260708d7e1dab681626f14cd13bdef75670/test/animate-notification-test.html#L56)):*
<details><summary><i>Previously, YuriyVaadin (Yuriy Yevstihnyeyev) wrote…</i></summary><blockquote>

Nit: `inmediatly` -> `immediately`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-notification/20)*

**Comment by platosha** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r4.
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-notification/20#-:-KzYK9hevH7pYTnHblh9:bnfp4nl)*

**Comment by web-padawan** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r2, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-notification/20#-:-KzYL5rI0i9KokfFeKoI:bnfp4nl)*

**Pull request merged**
