### PR TITLE
Remove <vaadin-overlay> dependency from <vaadin-notification-overlay>

### LINKED ISSUE #30: Consider moving part=content to the card elements
Styling the notification card is different from other overlay elements (:host vs [part=”content”]). It’s understandable from the implementation perspective, but for the developer it’s a bit unexpected, and means you can’t use a shared style module for all overlays (not a blocker, but causes some copy-paste code).

### PR DESCRIPTION
**Pull request by platosha**
Fixes #30

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-notification/32)

### CODE REVIEW

**Comment by YuriyVaadin** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-notification/32)*

**Comment by YuriyVaadin** [comment]
There is a problem with `Binding the opened property` demo when you quick checking/unchecking button (due to animation).
`Interecting With Content` demo is not working. 
Other than that awesome job! :thumbsup: 

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-notification/32#-:-L0K2CPaytcdlYIK0sPJ:b17yh5v)*

**Comment by web-padawan** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[vaadin-notification.html, line 224 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-notification/32#-L0K58N8x8fzPlrlzoWD:-L0K58N8x8fzPlrlzoWE:bxtrskq) ([raw file](https://github.com/vaadin/vaadin-notification/blob/882133730536c02d19b5ffcafaca66832e8158d1/vaadin-notification.html#L224)):*
> ```HTML
>         ready() {
>           super.ready();
>           this.modeless = true;
> ```

nit: `ready` can be now removed completely unless we need it for some reason

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-notification/32)*

**Comment by platosha** [comment]
Well, this seems to be incomplete considering the issue comments. Let me make the former overlay parts in the card before further review.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-notification/32#-:-L0KCIUCe-hcCE2kdGqm:bt0rtnp)*

**Comment by manolo** [comment]
Q: Is it necessary to remove overlay dependency here to fix #30? 
I feel that we are copying and pasting many code from the overlay component like the hack for iOS, that we need to maintain twice . An alternative if we don't need some features like focus-trap or modal, could be to move shared code to a lighter component or mixin in the overlay repo

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-notification/32#-:-L0NrHoeaNIIpuj8sZHt:b-r3fgqw)*

**Comment by YuriyVaadin** [comment]
Reviewed 2 of 3 files at r2, 1 of 1 files at r3.
Review status: 5 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-notification.html, line 224 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-notification/32#-L0K58N8x8fzPlrlzoWD:-L0PLQoAV29XotZh5SB8:b-896fix) ([raw file](https://github.com/vaadin/vaadin-notification/blob/882133730536c02d19b5ffcafaca66832e8158d1/vaadin-notification.html#L224)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

nit: `ready` can be now removed completely unless we need it for some reason
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-notification/32)*

**Comment by web-padawan** [comment]
Reviewed 3 of 5 files at r1, 2 of 3 files at r2, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-notification/32)*

**Comment by manolo** [comment]
1.- Notifications in the middle are not horizontally centered but covering all the desktop area. That is quite different to how top-centered or bottom-centered are displayed
2.- When there are top or bottom stretched  notifications, middle notifications are not aligned in the middle of the screen

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-notification/32#-:-L0ctMWd7Qk4HsFTW6JQ:bz9e7vd)*

**Comment by manolo** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[vaadin-notification.html, line 354 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-notification/32#-L0cupAYdbwmTOmJ-nz2:-L0cupAYdbwmTOmJ-nz3:b-fv1slj) ([raw file](https://github.com/vaadin/vaadin-notification/blob/f569d74e3b1ed2e2ba861a1708ac11b1c48813b5/vaadin-notification.html#L354)):*
> ```HTML
> 
>           this._card.slot = region;
>           if (this._overlay.firstElementChild &&
> ```

Why is necessary to do this programatically instead of using flex ?  flex seems more versatile and simpler

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-notification/32)*

**Comment by web-padawan** [comment]
The notification element no longer has shadow parts, so the whole Styling section containing link to ThemableMixin docs could be removed.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-notification/32#-:-L0cuwuJQh8pXlQQAOAu:b-3v1omd)*

**Comment by YuriyVaadin** [comment]
@manolo 

1. default theme is not no be judged here, as it would be replaced with Valo right after this PR. The cards sizing will be redefined by Valo theme anyway.

2. In the block context, the alignment of the cards can be set using `margin-left: auto; margin-right: auto;` on the card host element. This is also to be defined by Valo.

>The notification element no longer has shadow parts...

I have updated the documentation

---

Review status: 4 of 6 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-notification/32#-:-L0dTUbRyEQqSsjk1gnk:b-jsvp7k)*

**Comment by tomivirkki** [comment]
:lgtm:

---

Reviewed 2 of 5 files at r1, 2 of 3 files at r2, 2 of 2 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-notification/32#-:-L0htKAPK4zFTGmNRlC-:bnfp4nl)*

**Comment by YuriyVaadin** [comment]
Reviewed 2 of 2 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-notification.html, line 354 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-notification/32#-L0cupAYdbwmTOmJ-nz2:-L0iKbL1X6k8noTd2h4B:bghw3s5) ([raw file](https://github.com/vaadin/vaadin-notification/blob/f569d74e3b1ed2e2ba861a1708ac11b1c48813b5/vaadin-notification.html#L354)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

Why is necessary to do this programatically instead of using flex ?  flex seems more versatile and simpler
</blockquote></details>

As Anton confirmed, this was done intentionally without flex. If we will change it, we will suppose to change the implementation as well.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-notification/32)*

**Pull request merged**
