### PR TITLE
Implement and use Valo theme by default

### PR DESCRIPTION
**Pull request by YuriyVaadin**
Fixes https://github.com/vaadin/components-team-tasks/issues/297 

Implement and use Valo theme by default

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-notification/35)

### CODE REVIEW

**Comment by web-padawan** [comment]
Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/vaadin-notification.html, line 83 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-notification/35#-L0jCxH-t8TeabnIffOu:-L0jCxH-t8TeabnIffOv:bphq6pk) ([raw file](https://github.com/vaadin/vaadin-notification/blob/082697076a4b28c699292ca363de71b22a23812a/src/vaadin-notification.html#L83)):*
> ```HTML
> </dom-module>
> 
> <dom-module id="vaadin-notification-card-default-theme" theme-for="vaadin-notification-card">
> ```

Are we going to keep default theme here? We have removed it for other elements, so we probably should move styles into the element's `<style>` tag instead.

---

*[theme/valo/vaadin-notification.html, line 3 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-notification/35#-L0jDU7uhi5BWeh12WAN:-L0jDU7uhi5BWeh12WAO:b-af0sdv) ([raw file](https://github.com/vaadin/vaadin-notification/blob/082697076a4b28c699292ca363de71b22a23812a/theme/valo/vaadin-notification.html#L3)):*
> ```HTML
> <link rel="import" href="../../../vaadin-valo-theme/color.html">
> <link rel="import" href="../../../vaadin-valo-theme/spacing.html">
> <link rel="import" href="../../../vaadin-valo-theme/style.html">
> ```

nit: missing `typography.html` import here

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-notification/35)*

**Comment by web-padawan** [comment]
Reviewed 2 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-notification/35)*

**Comment by YuriyVaadin** [comment]
Review status: 6 of 8 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/vaadin-notification.html, line 83 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-notification/35#-L0jCxH-t8TeabnIffOu:-L0o8r6E3vePZMJwQlK4:b-896fix) ([raw file](https://github.com/vaadin/vaadin-notification/blob/082697076a4b28c699292ca363de71b22a23812a/src/vaadin-notification.html#L83)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

Are we going to keep default theme here? We have removed it for other elements, so we probably should move styles into the element's `<style>` tag instead.
</blockquote></details>

Done.

---

*[theme/valo/vaadin-notification.html, line 3 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-notification/35#-L0jDU7uhi5BWeh12WAN:-L0o8t8ImCZltkI4RFQM:b-896fix) ([raw file](https://github.com/vaadin/vaadin-notification/blob/082697076a4b28c699292ca363de71b22a23812a/theme/valo/vaadin-notification.html#L3)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

nit: missing `typography.html` import here
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-notification/35)*

**Comment by web-padawan** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-notification/35#-:-L0o97csgHvhSLVvO-O2:bnfp4nl)*

**Comment by jouni** [comment]
Are old notifications being detached/reattached when new ones get added? All previous notifications run their “enter“ animation when I add new ones.

**Comment by jouni** [comment]
Nit: use vaadin-button in the advanced demo, and add a bit more width for the duration text-field so that the default 3000 fits in without clipping (you could use the `theme="align-right"` variation as well).

**Comment by tomivirkki** [comment]
:lgtm:

---

Reviewed 3 of 7 files at r1, 1 of 2 files at r2, 1 of 1 files at r3, 3 of 3 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-notification/35#-:-L0yZ7gyphzuqqO6grk_:bnfp4nl)*

**Pull request merged**
