### PR TITLE
Set column-reverse direction for top notifications

### LINKED ISSUE #40: Stacking behavior is inconsistent between top and bottom positions
**Top**: new notifications get added at the bottom of the stack, *keeping previous ones in place*

**Bottom**: new notifications get added at the bottom of the stack, *pushing previous ones up*

The behavior of the top position is nicer because the previous notifications do not jump suddenly when a new one comes in. But, the behavior of the bottom position was the original intention, that the latest notification would always be “closest” to the viewport edge.

### PR DESCRIPTION
**Pull request by samiheikki**
Fixes #40

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-notification/50)

### CODE REVIEW

**Comment by jouni** [comment]
We should avoid using a flex container for the regions, as we want the margins of the notification cards to collapse.

**Comment by samiheikki** [comment]
Got it. I'll change tomorrow.

**Comment by samiheikki** [comment]
Well "tomorrow" was delayed quite a lot. But now it no longer uses flexbox.

**Comment by platosha** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/vaadin-notification/50#-L5ntkNWGvN41I9NFlig:-L5ntkNWGvN41I9NFlih:bqyjact) (no related file):*
Missing regression tests.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-notification/50)*

**Comment by samiheikki** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/vaadin-notification/50#-L5ntkNWGvN41I9NFlig:-L6HguGtJQOBfVd9z0Vq:b-886gsx) (no related file):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

Missing regression tests.
</blockquote></details>

Fixed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-notification/50)*

**Comment by platosha** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/vaadin-notification/50#-L5ntkNWGvN41I9NFlig:-L6LSXP86UQDh80ytXF4:b56yds) (no related file):*
<details><summary><i>Previously, samiheikki (Sami Suo-Heikki) wrote…</i></summary><blockquote>

Fixed
</blockquote></details>

The linter is complaining about the test:

```
/home/travis/build/vaadin/vaadin-notification/test/multiple-notification-test.html-script-1
  106:15  error  'region' is assigned a value but never used  no-unused-vars
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-notification/50)*

**Comment by samiheikki** [comment]
Failing test seems unrelated to this 🤔 And seems to be a bit random as well and at least on my FF 58 works if I add 1 millisecond timeout here https://github.com/vaadin/vaadin-notification/blob/master/test/multiple-notification-test.html#L89 @platosha WDYT?

**Comment by platosha** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[a discussion](https://beta.reviewable.io/reviews/vaadin/vaadin-notification/50#-L5ntkNWGvN41I9NFlig:-L6paHEkDvIPjmkmTceF:b2l86mr) (no related file):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

The linter is complaining about the test:

```
/home/travis/build/vaadin/vaadin-notification/test/multiple-notification-test.html-script-1
  106:15  error  'region' is assigned a value but never used  no-unused-vars
```
</blockquote></details>

OK this issue was fixed

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-notification/50)*

**Comment by platosha** [comment]
Indeed seems to be unrelated with the PR. Although I couldn’t reproduce this on master.

Fine to relax the test timeout if that helps.

Otherwise :lgtm: 

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-notification/50#-:-L6pueQI4bKILLUg1BEs:b8hejj4)*

**Comment by web-padawan** [comment]
:lgtm:

I'm merging this. We'll have to figure out how to fix tests on master, probably timeout would help.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-notification/50#-:-L6pxdUvYjcXG3LHHJXZ:b-v8m7l1)*

**Pull request merged**
