### PR TITLE
Implement MVP

### LINKED ISSUE #4: MVP
- Notification uses a single `<vaadin-notification-overlay>` (`<vaadin-overlay>` extension)
- Opening a notification closes any currently open notification
  - Store a reference to currently open notification element as a private property in `Vaadin.NotificationElement`
  - If there is an open notification, wait a while before opening a new one so any closing animation of the previous one has a chance to finish
    - Default style doesn't need to animate
- Should be animatable (by Valo)

API suggestion:
I assume the primary API we offer is declarative, something like:
```
<vaadin-notification duration="0" persist>
  <template>
    <p>Content</p>
  </template>
</vaadin-notification>
```
Using from JavaScript should also work:

```
// Can we have constructor parameters? 
// This is possibly overkill, as `textContent/innerText` and `innerHTML` are also available
const notify = new Vaadin.NotificationElement('Content'); // or document.createElement('vaadin-notification');
notify.innerHTML = '<template><p>Content</p></template>';
document.body.appendChild(notify);
notify.show();
```

MVP properties:
- `duration` default 3000
- `opened`

MVP functions:
- `open()`
- `close()`

Generic MVP requirements in https://sites.google.com/a/vaadin.com/elements-wiki/workflow

### PR DESCRIPTION
**Pull request by limonte**
Fixes #4

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-notification/6)

### CODE REVIEW

**Comment by tomivirkki** [comment]
Review status: 0 of 16 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[vaadin-notification.html, line 124 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-notification/6#-Kxs5L6iyI98TPNQ7m4t:-Kxs5L6iyI98TPNQ7m4u:bfmo75w) ([raw file](https://github.com/vaadin/vaadin-notification/blob/6c51734aff7f0f36d40f6955bd6742fa2b8722a2/vaadin-notification.html#L124)):*
> ```HTML
> 
>               // remove ID to avoid app styles applied to the overlay
>               this.$.overlay.removeAttribute('id');
> ```

Rather than dynamically removing the id, would be cleaner not to define the id at all. You can get store a reference to the overlay in `ready()`

---

*[vaadin-notification.html, line 127 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-notification/6#-Kxs5n_Q71_lf4R60Wcx:-Kxs5n_Q71_lf4R60Wcy:bt9ehf7) ([raw file](https://github.com/vaadin/vaadin-notification/blob/6c51734aff7f0f36d40f6955bd6742fa2b8722a2/vaadin-notification.html#L127)):*
> ```HTML
> 
>               // a11y
>               this.$.overlay.setAttribute('aria-label', this.$.overlay.shadowRoot.querySelector('[part="content"]').textContent);
> ```

Can't we get textContent from `this._instance.root` here instead?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-notification/6)*

**Comment by Toshegg** [comment]
:lgtm:

---

Review status: 0 of 16 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-notification/6#-:-Kxw-rS2oHYQAWgkBG6u:bnfp4nl)*

**Comment by limonte** [comment]
Review status: 0 of 16 files reviewed at latest revision, 2 unresolved discussions.

---

*[vaadin-notification.html, line 124 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-notification/6#-Kxs5L6iyI98TPNQ7m4t:-Kxw59ZB7bAgFXTT_9Zm:b-896fix) ([raw file](https://github.com/vaadin/vaadin-notification/blob/6c51734aff7f0f36d40f6955bd6742fa2b8722a2/vaadin-notification.html#L124)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Rather than dynamically removing the id, would be cleaner not to define the id at all. You can get store a reference to the overlay in `ready()`
</blockquote></details>

Done.

---

*[vaadin-notification.html, line 127 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-notification/6#-Kxs5n_Q71_lf4R60Wcx:-Kxw5AYwu5JxocNXShiG:b-m60ssm) ([raw file](https://github.com/vaadin/vaadin-notification/blob/6c51734aff7f0f36d40f6955bd6742fa2b8722a2/vaadin-notification.html#L127)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Can't we get textContent from `this._instance.root` here instead?
</blockquote></details>

Unfortunately, `this._instance.root.textContent` returns empty string here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-notification/6)*

**Comment by tomivirkki** [comment]
*[vaadin-notification.html, line 127 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-notification/6#-Kxs5n_Q71_lf4R60Wcx:-KxwFyVhL_rjv0jjQ3Qy:btxpdel) ([raw file](https://github.com/vaadin/vaadin-notification/blob/6c51734aff7f0f36d40f6955bd6742fa2b8722a2/vaadin-notification.html#L127)):*
<details><summary><i>Previously, limonte (Limon Monte) wrote…</i></summary><blockquote>

Unfortunately, `this._instance.root.textContent` returns empty string here.
</blockquote></details>

It seems that it should be read before it's added as the overlay's content. `this._instance.root.textContent`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-notification/6)*

**Comment by limonte** [comment]
Review status: 0 of 16 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-notification.html, line 127 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-notification/6#-Kxs5n_Q71_lf4R60Wcx:-KxwKJUJog2FhJRAj2AS:b-reuzq8) ([raw file](https://github.com/vaadin/vaadin-notification/blob/6c51734aff7f0f36d40f6955bd6742fa2b8722a2/vaadin-notification.html#L127)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

It seems that it should be read before it's added as the overlay's content. `this._instance.root.textContent`
</blockquote></details>

Oh, thanks! I also added `.trim()`

Test for `aria-label` added.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-notification/6)*

**Comment by manolo** [comment]
I can see here a problem, when you use the component declaratively with `opened`  the notification correctly is shown, and closed after 3 seconds, but pointer-events remain set in body, making the page unusable.

Also, the screenshot should lies, it should match the code block in readme, and it's not styled. 

---

Review status: 0 of 16 files reviewed at latest revision, 16 unresolved discussions.

---

*[vaadin-notification.html, line 15 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-notification/6#-Kxwwh5E8D-XjVNYMNV_:-Kxwwh5E8D-XjVNYMNVa:bguuu0y) ([raw file](https://github.com/vaadin/vaadin-notification/blob/afcab391dbfedc9457e51066a7b4f756dcb82181/vaadin-notification.html#L15)):*
> ```HTML
>       :host {
>         align-items: flex-start;
>         justify-content: flex-end;
> ```

I miss some padding here (ping @jouni). Normally we add some padding to our default themes, in order to look fine if the user don't want any theme

---

*[vaadin-notification.html, line 25 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-notification/6#-KxwtijZbrU3u4jz9Pld:-KxwtijZbrU3u4jz9Ple:b-5ox5h0) ([raw file](https://github.com/vaadin/vaadin-notification/blob/afcab391dbfedc9457e51066a7b4f756dcb82181/vaadin-notification.html#L25)):*
> ```HTML
>     <style>
>       :host {
>         display: inline-block;
> ```

Is this actually needed, I guess we can remove this block.

---

*[vaadin-notification.html, line 71 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-notification/6#-KxwwR8FzWxiTefqKNtd:-KxwwR8FzWxiTefqKNte:b-4x59y8) ([raw file](https://github.com/vaadin/vaadin-notification/blob/afcab391dbfedc9457e51066a7b4f756dcb82181/vaadin-notification.html#L71)):*
> ```HTML
>        * @demo demo/index.html
>        */
>       class NotificationElement extends (class extends Polymer.Element {}) {
> ```

Nice hack ! 

---

*[vaadin-notification.html, line 97 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-notification/6#-Kxww0Ggsf4iQZN2YqW3:-Kxww0Ggsf4iQZN2YqW4:bq1zkcm) ([raw file](https://github.com/vaadin/vaadin-notification/blob/afcab391dbfedc9457e51066a7b4f756dcb82181/vaadin-notification.html#L97)):*
> ```HTML
>             },
> 
>             _contentTemplate: Object
> ```

We don't need this, since it's only used in a block

---

*[vaadin-notification.html, line 117 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-notification/6#-Kxww7W05W-rx9b63dxt:-Kxww7W05W-rx9b63dxu:by9k725) ([raw file](https://github.com/vaadin/vaadin-notification/blob/afcab391dbfedc9457e51066a7b4f756dcb82181/vaadin-notification.html#L117)):*
> ```HTML
>           if (opened) {
>             if (!this._instance) {
>               this._contentTemplate = this.querySelector('template');
> ```

`this._contentTemplate` ->  `const template` 

---

*[vaadin-notification.html, line 133 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-notification/6#-Kxwv74nntiO--aJVAll:-Kxwv74nntiO--aJVAlm:bo0jhp1) ([raw file](https://github.com/vaadin/vaadin-notification/blob/afcab391dbfedc9457e51066a7b4f756dcb82181/vaadin-notification.html#L133)):*
> ```HTML
> 
>             if (this.duration > 0) {
>               this._durationTimeout = setTimeout(() => {
> ```

`setTimeout` returns an id, probably this variable should be renamed to `_durationTimeoutId` or if we don't have more timeouts in the component just `_timeoutId` 

---

*[vaadin-notification.html, line 137 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-notification/6#-Kxwuhoru5YaZ9Y3H8r4:-Kxwuhoru5YaZ9Y3H8r5:bsa9xis) ([raw file](https://github.com/vaadin/vaadin-notification/blob/afcab391dbfedc9457e51066a7b4f756dcb82181/vaadin-notification.html#L137)):*
> ```HTML
>               }, this.duration);
>             } else {
>               this._durationTimeout = null;
> ```

we don't need an object here, undefined is ok `delete this._durationTimeout`

---

*[demo/notification-basic-demos.html, line 10 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-notification/6#-KxwqnK5nfNevN-JBljU:-KxwqnK5nfNevN-JBljV:b-6ce1z4) ([raw file](https://github.com/vaadin/vaadin-notification/blob/afcab391dbfedc9457e51066a7b4f756dcb82181/demo/notification-basic-demos.html#L10)):*
> ```HTML
>     </style>
> 
>     <h3>Simple Notification</h3>
> ```

This is not a simple notification, it needs a bound context to work. To me this section should read 'Binding the `opened` property' or similar.

Simple Notification content should be something like:

```
        <vaadin-notification opened>
          <template>
            This notification Opens on loading the page and closes after a little while.
          </template>
        </vaadin-notification>
```

---

*[demo/notification-basic-demos.html, line 18 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-notification/6#-Kxwr9U8kVR8G4VdC-YX:-Kxwr9U8kVR8G4VdC-YY:b-ahghxm) ([raw file](https://github.com/vaadin/vaadin-notification/blob/afcab391dbfedc9457e51066a7b4f756dcb82181/demo/notification-basic-demos.html#L18)):*
> ```HTML
>             <vaadin-notification opened="{{notificationOpened}}">
>               <template>
>                 Your work has been saved
> ```

I'd rather that the notification describes what it does like

'The checkbox stays checked the time this notification is shown' 

---

*[demo/notification-basic-demos.html, line 24 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-notification/6#-KxwyQb9ANZcJ8sAWdC0:-KxwyQb9ANZcJ8sAWdC1:b-gqaxu7) ([raw file](https://github.com/vaadin/vaadin-notification/blob/afcab391dbfedc9457e51066a7b4f756dcb82181/demo/notification-basic-demos.html#L24)):*
> ```HTML
>         </dom-bind>
>       </template>
>     </vaadin-demo-snippet>
> ```

I miss a demo with arbitrary html

```
        <vaadin-notification opened>
          <template>
            <h3> Notice <h3>
            This notification has html content
          </template>
        </vaadin-notification>
```

---

*[demo/notification-basic-demos.html, line 32 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-notification/6#-KxwrauCH5MPEwLVXDX1:-KxwrauCH5MPEwLVXDX2:b-pz1lq9) ([raw file](https://github.com/vaadin/vaadin-notification/blob/afcab391dbfedc9457e51066a7b4f756dcb82181/demo/notification-basic-demos.html#L32)):*
> ```HTML
>         <script>
>           function showNotification() {
>             const notify = document.createElement('vaadin-notification');
> ```

This creates  new notification instances each time it's clicked. I think it might reuse the same instance instead.

In addition, behaviour of the button is odd, because you need to click twice when the notification is open in order to create a new notification.

---

*[test/index.html, line 16 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-notification/6#-KxwsQuwU6EKRcx7elOd:-KxwsQuwU6EKRcx7elOe:boqmyec) ([raw file](https://github.com/vaadin/vaadin-notification/blob/afcab391dbfedc9457e51066a7b4f756dcb82181/test/index.html#L16)):*
> ```HTML
> 
>     WCT.loadSuites([
>       'vaadin-notification_test.html'
> ```

nit: we don't use underscores in our file names. Use hyphen instead.

---

*[test/vaadin-notification_test.html, line 45 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-notification/6#-KxwspLxY6FTxqeWx8Qv:-KxwspLxY6FTxqeWx8Qw:b-bamaxy) ([raw file](https://github.com/vaadin/vaadin-notification/blob/afcab391dbfedc9457e51066a7b4f756dcb82181/test/vaadin-notification_test.html#L45)):*
> ```HTML
>       });
> 
>       describe('methods', () => {
> ```

I miss methods checking that the overlay is actually in the dom and visible. Also that the content is correctly shown in the overlay.

---

*[test/vaadin-notification_test.html, line 66 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-notification/6#-Kxwt5BjHnXELzDta7dD:-Kxwt5BjHnXELzDta7dE:blo3gz0) ([raw file](https://github.com/vaadin/vaadin-notification/blob/afcab391dbfedc9457e51066a7b4f756dcb82181/test/vaadin-notification_test.html#L66)):*
> ```HTML
>             expect(notification.opened).to.eql(false);
>             done();
>           }, 10);
> ```

I would add a milliseconds here, to guarantee that this timeout could not be executed just before the other one.

---

*[test/vaadin-notification_test.html, line 72 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-notification/6#-Kxwu8wZjWA53gm2UEcC:-Kxwu8wZjWA53gm2UEcD:b6lpllw) ([raw file](https://github.com/vaadin/vaadin-notification/blob/afcab391dbfedc9457e51066a7b4f756dcb82181/test/vaadin-notification_test.html#L72)):*
> ```HTML
>           notification.duration = -10;
>           notification.open();
>           expect(notification._durationTimeout).to.be.null;
> ```

Change null with undefined

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-notification/6#-:-KxwxKDdF73KgTeQRY82:briuftu)*

**Comment by manolo** [comment]
>  when you use the component declaratively with opened the notification correctly is shown

That was before I fetched your changes in r2 to this PR. It was because in r1 you were using `no-modal`, now that issue is fixed, but there is a new issue:  when you have a `<vaadin-notification opened>` opened attribute observer is called before ready, hence `this._overlay` is not defined

---

Review status: 0 of 16 files reviewed at latest revision, 15 unresolved discussions.

---

*[vaadin-notification.html, line 111 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-notification/6#-KxyHlEgZ9qZthx3bnC5:-KxyHlEgZ9qZthx3bnC6:bfrkhcm) ([raw file](https://github.com/vaadin/vaadin-notification/blob/afcab391dbfedc9457e51066a7b4f756dcb82181/vaadin-notification.html#L111)):*
> ```HTML
>         ready() {
>           super.ready();
>           this._overlay = this.shadowRoot.querySelector('vaadin-notification-overlay');
> ```

Please rollback this change, or initialise the `_overlay` in a different phase, otherwise the component fails in `_openedChanged` because a null exception when polymer sets the `opened` property 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-notification/6#-:-KxyH4U5GX7EsrAgDznS:b-6a75gw)*

**Comment by manolo** [comment]
Review status: 0 of 16 files reviewed at latest revision, 16 unresolved discussions.

---

*[vaadin-notification.html, line 127 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-notification/6#-Ky-OovPkvP7ijOjb0KW:-Ky-OovPkvP7ijOjb0KX:b-ebjdgr) ([raw file](https://github.com/vaadin/vaadin-notification/blob/afcab391dbfedc9457e51066a7b4f756dcb82181/vaadin-notification.html#L127)):*
> ```HTML
> 
>               // a11y
>               this._overlay.setAttribute('aria-label', this._instance.root.textContent.trim());
> ```

I see, `this._overlay` is only used here, so you can query the dom at this point and fix the null issue when setting opened in declarative. Thus the `ready()` block can be removed

```
   const overlay = this.shadowRoot.querySelector('vaadin-notification-overlay');
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-notification/6)*

**Comment by limonte** [comment]
Review status: 0 of 16 files reviewed at latest revision, 17 unresolved discussions.

---

*[vaadin-notification.html, line 15 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-notification/6#-Kxwwh5E8D-XjVNYMNV_:-Ky-mXrUZrfZHrHHptfS:b-mqb1t3) ([raw file](https://github.com/vaadin/vaadin-notification/blob/afcab391dbfedc9457e51066a7b4f756dcb82181/vaadin-notification.html#L15)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

I miss some padding here (ping @jouni). Normally we add some padding to our default themes, in order to look fine if the user don't want any theme
</blockquote></details>

Copied the 5px padding from the dialog.

---

*[vaadin-notification.html, line 25 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-notification/6#-KxwtijZbrU3u4jz9Pld:-Ky-nBy56OMtNKPfPGn2:b-3frmrb) ([raw file](https://github.com/vaadin/vaadin-notification/blob/afcab391dbfedc9457e51066a7b4f756dcb82181/vaadin-notification.html#L25)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

Is this actually needed, I guess we can remove this block.
</blockquote></details>

Not needed, removed.

---

*[vaadin-notification.html, line 71 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-notification/6#-KxwwR8FzWxiTefqKNtd:-Ky-nIMmxEIPJO8p2pzG:bk2tpk3) ([raw file](https://github.com/vaadin/vaadin-notification/blob/afcab391dbfedc9457e51066a7b4f756dcb82181/vaadin-notification.html#L71)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

Nice hack ! 
</blockquote></details>

(c) platosha

---

*[vaadin-notification.html, line 97 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-notification/6#-Kxww0Ggsf4iQZN2YqW3:-Ky-nS1MrBjkXnYgppQx:bss4a2b) ([raw file](https://github.com/vaadin/vaadin-notification/blob/afcab391dbfedc9457e51066a7b4f756dcb82181/vaadin-notification.html#L97)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

We don't need this, since it's only used in a block
</blockquote></details>

Removed.

---

*[vaadin-notification.html, line 111 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-notification/6#-KxyHlEgZ9qZthx3bnC5:-Ky-tPrh7Te7G1p5T_yn:bp3aow6) ([raw file](https://github.com/vaadin/vaadin-notification/blob/afcab391dbfedc9457e51066a7b4f756dcb82181/vaadin-notification.html#L111)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

Please rollback this change, or initialise the `_overlay` in a different phase, otherwise the component fails in `_openedChanged` because a null exception when polymer sets the `opened` property 
</blockquote></details>

Reverted.

---

*[vaadin-notification.html, line 117 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-notification/6#-Kxww7W05W-rx9b63dxt:-Ky-nuPPUz97X4UWVhNE:bb7f2mf) ([raw file](https://github.com/vaadin/vaadin-notification/blob/afcab391dbfedc9457e51066a7b4f756dcb82181/vaadin-notification.html#L117)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

`this._contentTemplate` ->  `const template` 
</blockquote></details>

done

---

*[vaadin-notification.html, line 127 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-notification/6#-Ky-OovPkvP7ijOjb0KW:-Ky-tXjCuofuJwZTzfRL:b-mlefyz) ([raw file](https://github.com/vaadin/vaadin-notification/blob/afcab391dbfedc9457e51066a7b4f756dcb82181/vaadin-notification.html#L127)):*
> this.shadowRoot.querySelector('vaadin-notification-overlay')

`this.shadowRoot.querySelector('vaadin-notification-overlay')` will return `null` because `vaadin-notification-overlay` is already in the body, not in the Shadow root of the element.

Done with:

```
const overlay = this.$['vaadin-notification-overlay']
```

---

*[vaadin-notification.html, line 133 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-notification/6#-Kxwv74nntiO--aJVAll:-Ky-o0usUjeK6wcz2dWX:b1ry8e5) ([raw file](https://github.com/vaadin/vaadin-notification/blob/afcab391dbfedc9457e51066a7b4f756dcb82181/vaadin-notification.html#L133)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

`setTimeout` returns an id, probably this variable should be renamed to `_durationTimeoutId` or if we don't have more timeouts in the component just `_timeoutId` 
</blockquote></details>

Renamed to `_durationTimeoutId`

---

*[vaadin-notification.html, line 137 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-notification/6#-Kxwuhoru5YaZ9Y3H8r4:-Ky-o7YFOCaMGwcfaix9:bb7f2mf) ([raw file](https://github.com/vaadin/vaadin-notification/blob/afcab391dbfedc9457e51066a7b4f756dcb82181/vaadin-notification.html#L137)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

we don't need an object here, undefined is ok `delete this._durationTimeout`
</blockquote></details>

done

---

*[demo/notification-basic-demos.html, line 10 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-notification/6#-KxwqnK5nfNevN-JBljU:-Ky-tppxUeTlaz4A4J6r:b2cbygh) ([raw file](https://github.com/vaadin/vaadin-notification/blob/afcab391dbfedc9457e51066a7b4f756dcb82181/demo/notification-basic-demos.html#L10)):*
> Binding the opened property

Done.

---

*[demo/notification-basic-demos.html, line 18 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-notification/6#-Kxwr9U8kVR8G4VdC-YX:-Ky-u0TQ_nSgJE4-XpY9:b-896fix) ([raw file](https://github.com/vaadin/vaadin-notification/blob/afcab391dbfedc9457e51066a7b4f756dcb82181/demo/notification-basic-demos.html#L18)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

I'd rather that the notification describes what it does like

'The checkbox stays checked the time this notification is shown' 
</blockquote></details>

Done.

---

*[demo/notification-basic-demos.html, line 24 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-notification/6#-KxwyQb9ANZcJ8sAWdC0:-Ky-u3vCB9b8EFW9UK19:b-a0stez) ([raw file](https://github.com/vaadin/vaadin-notification/blob/afcab391dbfedc9457e51066a7b4f756dcb82181/demo/notification-basic-demos.html#L24)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

I miss a demo with arbitrary html

```
        <vaadin-notification opened>
          <template>
            <h3> Notice <h3>
            This notification has html content
          </template>
        </vaadin-notification>
```
</blockquote></details>

Right, added

---

*[demo/notification-basic-demos.html, line 32 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-notification/6#-KxwrauCH5MPEwLVXDX1:-Ky-x_BtcKwsIL3KR-Ze:b-mq885w) ([raw file](https://github.com/vaadin/vaadin-notification/blob/afcab391dbfedc9457e51066a7b4f756dcb82181/demo/notification-basic-demos.html#L32)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

This creates  new notification instances each time it's clicked. I think it might reuse the same instance instead.

In addition, behaviour of the button is odd, because you need to click twice when the notification is open in order to create a new notification.


</blockquote></details>

This is a good example for the upcoming multiple notifications feature. I would leave it like this. 

---

*[test/index.html, line 16 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-notification/6#-KxwsQuwU6EKRcx7elOd:-Ky-oAYFWgrJRlqsAauv:byjg5tx) ([raw file](https://github.com/vaadin/vaadin-notification/blob/afcab391dbfedc9457e51066a7b4f756dcb82181/test/index.html#L16)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

nit: we don't use underscores in our file names. Use hyphen instead.
</blockquote></details>

We do. 

- https://github.com/vaadin/vaadin-button/tree/master/test
- https://github.com/vaadin/vaadin-checkbox/tree/master/test
- https://github.com/vaadin/vaadin-split-layout/tree/master/test

Also, this is the matter of taste.

---

*[test/vaadin-notification_test.html, line 45 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-notification/6#-KxwspLxY6FTxqeWx8Qv:-Ky00KfHaOi_5vHQhlnB:b-27tg9d) ([raw file](https://github.com/vaadin/vaadin-notification/blob/afcab391dbfedc9457e51066a7b4f756dcb82181/test/vaadin-notification_test.html#L45)):*
> I miss methods checking that the overlay is actually in the dom and visible. 

Added.

> Also that the content is correctly shown in the overlay.

This is the overlay responsibility, should not be tested here.

---

*[test/vaadin-notification_test.html, line 66 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-notification/6#-Kxwt5BjHnXELzDta7dD:-Ky-xo7ywgE2YNwqv6Ju:b-3wj9xx) ([raw file](https://github.com/vaadin/vaadin-notification/blob/afcab391dbfedc9457e51066a7b4f756dcb82181/test/vaadin-notification_test.html#L66)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

I would add a milliseconds here, to guarantee that this timeout could not be executed just before the other one.
</blockquote></details>

I would not. I do expect notification closed after exactly 10ms.

---

*[test/vaadin-notification_test.html, line 72 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-notification/6#-Kxwu8wZjWA53gm2UEcC:-Ky-xkURRoXKgNpf-Uq-:b-a2ujfl) ([raw file](https://github.com/vaadin/vaadin-notification/blob/afcab391dbfedc9457e51066a7b4f756dcb82181/test/vaadin-notification_test.html#L72)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

Change null with undefined
</blockquote></details>

Changed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-notification/6)*

**Comment by platosha** [comment]
Review status: 0 of 16 files reviewed at latest revision, 17 unresolved discussions.

---

*[vaadin-notification.html, line 27 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-notification/6#-Ky1S5rdVvjpI63mK9kV:-Ky1S5reZaNrbuZHh9qP:b5bngh4) ([raw file](https://github.com/vaadin/vaadin-notification/blob/e9ac06ba7a6d340605f5462a1a537c0f13c41b2b/vaadin-notification.html#L27)):*
> ```HTML
> <dom-module id="vaadin-notification">
>   <template>
>     <vaadin-notification-overlay id="vaadin-notification-overlay"
> ```

Maybe camelCase `id="vaadinNotificationOverlay"`? Then it’s easier to use as a dollar helper key:

```javascript
this.$.vaadinNotificationOverlay`
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-notification/6)*

**Comment by tomivirkki** [comment]
*[vaadin-notification.html, line 27 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-notification/6#-Ky1S5rdVvjpI63mK9kV:-Ky1W0hQ4_uEnAvxbJTj:bou4uja) ([raw file](https://github.com/vaadin/vaadin-notification/blob/e9ac06ba7a6d340605f5462a1a537c0f13c41b2b/vaadin-notification.html#L27)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

Maybe camelCase `id="vaadinNotificationOverlay"`? Then it’s easier to use as a dollar helper key:

```javascript
this.$.vaadinNotificationOverlay`
```
</blockquote></details>

Camel case in html sounds nasty... I'd maybe even prefer lowercase over that `this.$.vaadinnotificationoverlay`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-notification/6)*

**Comment by limonte** [comment]
Review status: 0 of 16 files reviewed at latest revision, 17 unresolved discussions.

---

*[vaadin-notification.html, line 27 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-notification/6#-Ky1S5rdVvjpI63mK9kV:-Ky1WDMTituonKLJloKP:bqnvaoh) ([raw file](https://github.com/vaadin/vaadin-notification/blob/e9ac06ba7a6d340605f5462a1a537c0f13c41b2b/vaadin-notification.html#L27)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Camel case in html sounds nasty... I'd maybe even prefer lowercase over that `this.$.vaadinnotificationoverlay`
</blockquote></details>

I prefer kebab-case for ids and class names: https://google.github.io/styleguide/htmlcssguide.html#ID_and_Class_Name_Delimiters

Matter of taste though, shouldn't be discussed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-notification/6)*

**Comment by tomivirkki** [comment]
*[vaadin-notification.html, line 27 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-notification/6#-Ky1S5rdVvjpI63mK9kV:-Ky1XhSbsftqxVC-0ZWJ:bv36zrx) ([raw file](https://github.com/vaadin/vaadin-notification/blob/e9ac06ba7a6d340605f5462a1a537c0f13c41b2b/vaadin-notification.html#L27)):*
<details><summary><i>Previously, limonte (Limon Monte) wrote…</i></summary><blockquote>

I prefer kebab-case for ids and class names: https://google.github.io/styleguide/htmlcssguide.html#ID_and_Class_Name_Delimiters

Matter of taste though, shouldn't be discussed.
</blockquote></details>

kebab-case could work :+1: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-notification/6)*

**Comment by manolo** [comment]
:lgtm:

---

Reviewed 14 of 17 files at r1, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[demo/notification-basic-demos.html, line 32 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-notification/6#-KxwrauCH5MPEwLVXDX1:-Ky1flQVOrZr5yx9Jaky:b2ftm1o) ([raw file](https://github.com/vaadin/vaadin-notification/blob/afcab391dbfedc9457e51066a7b4f756dcb82181/demo/notification-basic-demos.html#L32)):*
<details><summary><i>Previously, limonte (Limon Monte) wrote…</i></summary><blockquote>

This is a good example for the upcoming multiple notifications feature. I would leave it like this. 
</blockquote></details>

Well for the MVP there is this spec, that  seems not covered

```
Opening a notification closes any currently open notification
Store a reference to currently open notification element as a private property in Vaadin.NotificationElement
If there is an open notification, wait a while before opening a new one so any closing animation of the previous one has a chance to finish
```

I thought this demo should be for that.
Not a blocker for this PR, the feature can be added later

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-notification/6#-:-Ky1hCXZlb9nDEF5U9tp:bnfp4nl)*

**Pull request merged**
