### PR TITLE
Add renderer

### LINKED ISSUE #76: Content renderer
Child of vaadin/components-team-tasks#365

See the spec: https://github.com/vaadin/components-team-tasks/issues/365#issuecomment-404149148

### PR DESCRIPTION
**Pull request by YuriyVaadin**
Fixes #76

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-notification/77)

### CODE REVIEW

**Comment by tomivirkki** [comment]
___
*[src/vaadin-notification.html, line 395 at r2](https://reviewable.io/reviews/vaadin/vaadin-notification/77#-LHY8NlS7Sr-Vcy1c8lf:-LHYBA00EEw_k5GM-srJ:bpt6p3r) ([raw file](https://github.com/vaadin/vaadin-notification/blob/2d8603a1ff4d70f89e080ab95d1918dd6860846e/src/vaadin-notification.html#L395)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

if we remove the second parameter we misalign this renderer with other elements renderers 
</blockquote></details>

Should the order of the arguments be reconsidered since "model" is not used everywhere?

**Comment by tomivirkki** [comment]
___
*[demo/notification-basic-demos.html, line 40 at r3](https://reviewable.io/reviews/vaadin/vaadin-notification/77#-LHbFYSH2uZKKT4sYhaO:-LHbFYSH2uZKKT4sYhaP:b-7eqhdp) ([raw file](https://github.com/vaadin/vaadin-notification/blob/6b56bd0abad34a5c58dd641c450b6add778eecb0/demo/notification-basic-demos.html#L40)):*
> ```HTML
>     <vaadin-demo-snippet id="notification-basic-demos-renderer-notification">
>       <template preserve-content>
>         <dom-bind id="bind-elm">
> ```

The renderer feature is a step towards reducing the users' necessity to use Polymer's proprietary APIs (so that the components would be more JS/framework user friendly). Using Polymer's "dom-bind + template" with Polymer-syntax bindings in the renderer demo doesn't serve the purpose.

**Comment by tomivirkki** [comment]
___
*[src/vaadin-notification.html, line 257 at r3](https://reviewable.io/reviews/vaadin/vaadin-notification/77#-LHbWzGj9eMiKTotxc6x:-LHbWzGj9eMiKTotxc6y:b-6xdbh4) ([raw file](https://github.com/vaadin/vaadin-notification/blob/6b56bd0abad34a5c58dd641c450b6add778eecb0/src/vaadin-notification.html#L257)):*
> ```HTML
>             /**
>              * Custom function for rendering the content of the overlay.
>              * Receives arguments `root`, `owner`
> ```

Why isn't "model" mentioned in this list but the argument is still documented below?

**Comment by sohrabtaee** [comment]
___
*[demo/notification-basic-demos.html, line 83 at r4](https://reviewable.io/reviews/vaadin/vaadin-notification/77#-LHgtC_YBzx4Gi_AGITx:-LHgtC_YBzx4Gi_AGITy:b-e7dr1i) ([raw file](https://github.com/vaadin/vaadin-notification/blob/1b99bbdadf3941cbe1220e949c1af36255336d31/demo/notification-basic-demos.html#L83)):*
> ```HTML
>         </script>
>       </template>
>     </vaadin-demo-snippet>saf
> ```

What is this "saf" after the closing tag?

**Comment by tomivirkki** [comment]
___
*[src/vaadin-notification.html, line 273 at r5](https://reviewable.io/reviews/vaadin/vaadin-notification/77#-LHiDxe77N8uyxpvDgHw:-LHiDxe77N8uyxpvDgHx:b-o30sc2) ([raw file](https://github.com/vaadin/vaadin-notification/blob/a2d0ac0f68d74355ac4944ad456d7fca3721c7d3/src/vaadin-notification.html#L273)):*
> ```HTML
>              * The template of the notification card content.
>              */
>             template: Object
> ```

Why is this new public API added?!!!

**Comment by tomivirkki** [comment]
___
*[test/notification-renderer-test.html, line 109 at r6](https://reviewable.io/reviews/vaadin/vaadin-notification/77#-LHm-Dr81Y0-9X06Mwk_:-LHm2twW7h-NNB6L7HBk:b-b312tr) ([raw file](https://github.com/vaadin/vaadin-notification/blob/727de31b91aa7bb323f4d216727c0800ce4e657d/test/notification-renderer-test.html#L109)):*
<details><summary><i>Previously, YuriyVaadin (Yuriy Yevstihnyeyev) wrote…</i></summary><blockquote>

Should I remove it in scope of this PR?
</blockquote></details>

We kind of agreed yesterday that it can be removed separately if it's already implemented (if the PR author prefers that).

**Pull request merged**
