### PR TITLE
Enable styling the notification overlay content from parent scope

### LINKED ISSUE #63: Simplify the overlay styling

### PR DESCRIPTION
**Pull request by YuriyVaadin**
Fixes #63

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-notification/65)

### CODE REVIEW

**Comment by web-padawan** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---

*[demo/notification-basic-demos.html, line 82 at r1](https://beta.reviewable.io/reviews/vaadin/vaadin-notification/65#-LANE099BnnvDXELfWXR:-LANE099BnnvDXELfWXS:b-sje6zj) ([raw file](https://github.com/vaadin/vaadin-notification/blob/644c7078f76fd44cad3cdc0f9272a9588f96e005/demo/notification-basic-demos.html#L82)):*
> ```HTML
>       <template preserve-content>
>         <style>
>           .customized {
> ```

consider a separate demo for this feature, in order to highlight it better

---

*[src/vaadin-notification.html, line 292 at r1](https://beta.reviewable.io/reviews/vaadin/vaadin-notification/65#-LANE8OS1MbvluWO6Sfa:-LANE8OS1MbvluWO6Sfb:bwm90m4) ([raw file](https://github.com/vaadin/vaadin-notification/blob/644c7078f76fd44cad3cdc0f9272a9588f96e005/src/vaadin-notification.html#L292)):*
> ```HTML
>               if (!template._Templatizer) {
>                 template._Templatizer = Polymer.Templatize.templatize(template, this, {
>                   instanceProps: this.instanceProps,
> ```

do we want to introduce `instanceProps` here?

---

*[src/vaadin-notification.html, line 301 at r1](https://beta.reviewable.io/reviews/vaadin/vaadin-notification/65#-LANF0ei721vWzmVnTDt:-LANF0ei721vWzmVnTDu:b3bgkoj) ([raw file](https://github.com/vaadin/vaadin-notification/blob/644c7078f76fd44cad3cdc0f9272a9588f96e005/src/vaadin-notification.html#L301)):*
> ```HTML
>               }
>               this._instance = new template._Templatizer({});
>               this._contentNodes = Array.from(this._instance.root.childNodes);
> ```

this is currently not used here

---

*[src/vaadin-notification.html, line 304 at r1](https://beta.reviewable.io/reviews/vaadin/vaadin-notification/65#-LANEhG1BAnBAm02f0s1:-LANEhG22Ts-xltUNZQ1:b-c8jndu) ([raw file](https://github.com/vaadin/vaadin-notification/blob/644c7078f76fd44cad3cdc0f9272a9588f96e005/src/vaadin-notification.html#L304)):*
> ```HTML
> 
>               const templateRoot = template.getRootNode();
>               this._isScoped = templateRoot !== document;
> ```

this should be declared in `properties` block. same for `_shadyStyleScope`

---

*[src/vaadin-notification.html, line 324 at r1](https://beta.reviewable.io/reviews/vaadin/vaadin-notification/65#-LANEMTdDXcGRKZLTE-m:-LANEMTdDXcGRKZLTE-n:b-h26azw) ([raw file](https://github.com/vaadin/vaadin-notification/blob/644c7078f76fd44cad3cdc0f9272a9588f96e005/src/vaadin-notification.html#L324)):*
> ```HTML
>                 if (!this._card.shadowRoot.querySelector('[part~="content"]').shadowRoot) {
>                   this._card.shadowRoot.querySelector('[part~="content"]').attachShadow({mode: 'open'});
>                   // FIXME(platosha): IronFocusablesHelper does only use legacy .root
> ```

notification does not use IronFocusablesHelper

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-notification/65)*

**Comment by web-padawan** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-notification/65)*

**Comment by web-padawan** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-notification/65)*

**Comment by web-padawan** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-notification/65)*

**Comment by tomivirkki** [comment]
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[src/vaadin-notification.html, line 255 at r4](https://beta.reviewable.io/reviews/vaadin/vaadin-notification/65#-LANs8vV-ca0pxGcH3Lt:-LANs8vV-ca0pxGcH3Lu:b-nk6hsd) ([raw file](https://github.com/vaadin/vaadin-notification/blob/9add163e9a3fba34cf5ab5e7c73333dc96ed9bcb/src/vaadin-notification.html#L255)):*
> ```HTML
>             },
> 
>             _isScoped: Boolean,
> ```

Doesn't need to be a property

---

*[src/vaadin-notification.html, line 257 at r4](https://beta.reviewable.io/reviews/vaadin/vaadin-notification/65#-LANs6OI51LvEN0kum5k:-LANs6OI51LvEN0kum5l:b-nk6hsd) ([raw file](https://github.com/vaadin/vaadin-notification/blob/9add163e9a3fba34cf5ab5e7c73333dc96ed9bcb/src/vaadin-notification.html#L257)):*
> ```HTML
>             _isScoped: Boolean,
> 
>             _shadyStyleScope: String
> ```

Doesn't need to be a property

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-notification/65)*

**Comment by tomivirkki** [comment]
:lgtm:

---

Reviewed 3 of 4 files at r2, 1 of 2 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[src/vaadin-notification.html, line 312 at r5](https://beta.reviewable.io/reviews/vaadin/vaadin-notification/65#-LARoeQp2El2grM3VeRF:-LARoZ_h8NtuXFUyCkgs:b-t4fbga) ([raw file](https://github.com/vaadin/vaadin-notification/blob/0664e3a577015201ba8617ca26c0a2bfdd9f9987/src/vaadin-notification.html#L312)):*
> ```HTML
>                 if (window.ShadyCSS && !window.ShadyCSS.nativeShadow) {
>                   // Shady DOM
>                   var _shadyStyleScope = templateRoot.host
> ```

Local variables don't need to be underscored, "var" => "const". Not a blocker.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-notification/65#-:-LARopJJ-wPbgEHU9qnv:bnfp4nl)*

**Comment by web-padawan** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-notification/65)*

**Comment by web-padawan** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-notification/65#-:-LARqymp-K_U8BosAvNl:bnfp4nl)*

**Comment by platosha** [comment]
Reviewed 3 of 4 files at r2, 1 of 2 files at r4, 1 of 1 files at r5.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[src/vaadin-notification.html, line 313 at r5](https://beta.reviewable.io/reviews/vaadin/vaadin-notification/65#-LAS5bpp9kk2pRott-tL:-LAS5bpq7HIMXVu7tmck:b-eed7d7) ([raw file](https://github.com/vaadin/vaadin-notification/blob/0664e3a577015201ba8617ca26c0a2bfdd9f9987/src/vaadin-notification.html#L313)):*
> ```HTML
>                   // Shady DOM
>                   var _shadyStyleScope = templateRoot.host
>                     && (templateRoot.host.getAttribute('is') || templateRoot.host.localName);
> ```

We shouldn’t take `is` from custom elements. See: https://github.com/vaadin/vaadin-overlay/pull/83/files

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-notification/65)*

**Comment by YuriyVaadin** [comment]
Review status: 3 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/vaadin-notification.html, line 312 at r5](https://beta.reviewable.io/reviews/vaadin/vaadin-notification/65#-LARoeQp2El2grM3VeRF:-LASK_lo19iybkUa3teL:bv16njd) ([raw file](https://github.com/vaadin/vaadin-notification/blob/0664e3a577015201ba8617ca26c0a2bfdd9f9987/src/vaadin-notification.html#L312)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Local variables don't need to be underscored, "var" => "const". Not a blocker.
</blockquote></details>

Not possible with latest update.

---

*[src/vaadin-notification.html, line 313 at r5](https://beta.reviewable.io/reviews/vaadin/vaadin-notification/65#-LAS5bpp9kk2pRott-tL:-LASKeCD8WgmXDJjy6jL:b-pu4do7) ([raw file](https://github.com/vaadin/vaadin-notification/blob/0664e3a577015201ba8617ca26c0a2bfdd9f9987/src/vaadin-notification.html#L313)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

We shouldn’t take `is` from custom elements. See: https://github.com/vaadin/vaadin-overlay/pull/83/files
</blockquote></details>

Updated accordingly.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-notification/65)*

**Comment by platosha** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r6, 1 of 1 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-notification/65#-:-LASaBaj0UhaghZ9DT7L:bnfp4nl)*

**Comment by web-padawan** [comment]
Reviewed 1 of 2 files at r6, 1 of 1 files at r7.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-notification/65)*

**Pull request merged**
