### PR TITLE
Combine vertical-align and horizontal-align into a single position property

### LINKED ISSUE #33: Combine vertical-align and horizontal-align into a single property
As there are two combinations which are not supported (middle+start and middle+end), it would be clearer for the developer if there was just a single property with a list of supported positions/locations.

### PR DESCRIPTION
**Pull request by YuriyVaadin**
fixes #33

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-notification/34)

### CODE REVIEW

**Comment by web-padawan** [comment]
Reviewed 5 of 6 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[vaadin-notification.html, line 272 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-notification/34#-L0dd7pUNXQ3W9z1o3uX:-L0dd7pUNXQ3W9z1o3uY:bl7o12z) ([raw file](https://github.com/vaadin/vaadin-notification/blob/39bb3f6bed9758cecbaa0dce29196ec4c064ff4a/vaadin-notification.html#L272)):*
> ```HTML
> 
>             /**
>              * Vertical and horizontal alignment of the notification in the viewport
> ```

BTW this can be probably simplified to just mention `Alignment of the notification`.
Not a blocker.

---

*[vaadin-notification.html, line 273 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-notification/34#-L0ddMiLz9IMZsg1XuJD:-L0ddMiLz9IMZsg1XuJE:bpjg2jd) ([raw file](https://github.com/vaadin/vaadin-notification/blob/39bb3f6bed9758cecbaa0dce29196ec4c064ff4a/vaadin-notification.html#L273)):*
> ```HTML
>             /**
>              * Vertical and horizontal alignment of the notification in the viewport
>              * Valid values are `top-stretch|top-start|top-center|top-end|middle|bottom-start|bottom-center|bottom-end|bottom-stretch`
> ```

BTW personally I would expect the same order for `top` and `bottom` vaules here, e. g. start-center-end-stretch
Not a blocker.

---

*[demo/notification-advanced-demos.html, line 46 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-notification/34#-L0dd_XheuOI_wYR2ATL:-L0dd_XheuOI_wYR2ATM:bpjg2jd) ([raw file](https://github.com/vaadin/vaadin-notification/blob/39bb3f6bed9758cecbaa0dce29196ec4c064ff4a/demo/notification-advanced-demos.html#L46)):*
> ```HTML
>                   <vaadin-radio-button name="radio-group" value="top-end">top-end</vaadin-radio-button>
>                   <vaadin-radio-button name="radio-group" value="middle">middle</vaadin-radio-button>
>                   <vaadin-radio-button name="radio-group" value="bottom-start">bottom-start</vaadin-radio-button>
> ```

BTW personally I would expect the same order for `top` and `bottom` vaules here, e. g. start-center-end-stretch
Not a blocker.

---

*[test/multiple-notification-test.html, line 114 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-notification/34#-L0dcZIjmVBQWWVD_IUd:-L0dcZIjmVBQWWVD_IUe:be9kvom) ([raw file](https://github.com/vaadin/vaadin-notification/blob/39bb3f6bed9758cecbaa0dce29196ec4c064ff4a/test/multiple-notification-test.html#L114)):*
> ```HTML
>           notifications.forEach(e => {
>             const position = e.getAttribute('position');
>             expect(e._card.slot).to.equal(position);
> ```

The line above can be removed and the test can be shortened to: 
```
 notifications.forEach(e => expect(e._card.slot).to.equal(e.position);
```

BTW I do not see any particular reason to use `getAttribute` here now, since the `position` property does not reflect to attribute.

---

*[test/multiple-notification-test.html, line 126 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-notification/34#-L0db_e6xzRHVzAjvUA8:-L0db_e6xzRHVzAjvUA9:bzbijzs) ([raw file](https://github.com/vaadin/vaadin-notification/blob/39bb3f6bed9758cecbaa0dce29196ec4c064ff4a/test/multiple-notification-test.html#L126)):*
> ```HTML
>         });
> 
>         it('should move notification if horizontal alignment part of the position changes', () => {
> ```

This second test now tests basically the same thing as the one above and therefore ca be removed. At the same time the remaining test should be renamed to e. g. 
```
should move notification if position changes
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-notification/34)*

**Comment by YuriyVaadin** [comment]
Review status: 4 of 6 files reviewed at latest revision, 5 unresolved discussions.

---

*[vaadin-notification.html, line 272 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-notification/34#-L0dd7pUNXQ3W9z1o3uX:-L0deVwo6K9h6knmfYEW:b-a2ujfl) ([raw file](https://github.com/vaadin/vaadin-notification/blob/39bb3f6bed9758cecbaa0dce29196ec4c064ff4a/vaadin-notification.html#L272)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

BTW this can be probably simplified to just mention `Alignment of the notification`.
Not a blocker.
</blockquote></details>

Changed.

---

*[vaadin-notification.html, line 273 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-notification/34#-L0ddMiLz9IMZsg1XuJD:-L0deX8HJEbPbSzGGD62:b-g0eium) ([raw file](https://github.com/vaadin/vaadin-notification/blob/39bb3f6bed9758cecbaa0dce29196ec4c064ff4a/vaadin-notification.html#L273)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

BTW personally I would expect the same order for `top` and `bottom` vaules here, e. g. start-center-end-stretch
Not a blocker.
</blockquote></details>

I have added them in such order intentionally, so it shows the order of displaying notifications (`top-stretch` on top of all others, `bottom-stretch` below all others)

---

*[demo/notification-advanced-demos.html, line 46 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-notification/34#-L0dd_XheuOI_wYR2ATL:-L0deot10gclmJYEYl91:b-g0eium) ([raw file](https://github.com/vaadin/vaadin-notification/blob/39bb3f6bed9758cecbaa0dce29196ec4c064ff4a/demo/notification-advanced-demos.html#L46)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

BTW personally I would expect the same order for `top` and `bottom` vaules here, e. g. start-center-end-stretch
Not a blocker.
</blockquote></details>

I have added them in such order intentionally, so it shows the order of displaying notifications (`top-stretch` on top of all others, `bottom-stretch` below all others)

---

*[test/multiple-notification-test.html, line 114 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-notification/34#-L0dcZIjmVBQWWVD_IUd:-L0deq8tF8UTJKcDDFhz:b-896fix) ([raw file](https://github.com/vaadin/vaadin-notification/blob/39bb3f6bed9758cecbaa0dce29196ec4c064ff4a/test/multiple-notification-test.html#L114)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

The line above can be removed and the test can be shortened to: 
```
 notifications.forEach(e => expect(e._card.slot).to.equal(e.position);
```

BTW I do not see any particular reason to use `getAttribute` here now, since the `position` property does not reflect to attribute.
</blockquote></details>

Done.

---

*[test/multiple-notification-test.html, line 126 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-notification/34#-L0db_e6xzRHVzAjvUA8:-L0deqthQV2qkn_CCBYN:b-896fix) ([raw file](https://github.com/vaadin/vaadin-notification/blob/39bb3f6bed9758cecbaa0dce29196ec4c064ff4a/test/multiple-notification-test.html#L126)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

This second test now tests basically the same thing as the one above and therefore ca be removed. At the same time the remaining test should be renamed to e. g. 
```
should move notification if position changes
```
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-notification/34)*

**Comment by web-padawan** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-notification/34#-:-L0dgAATjSFzfwMcWBvO:bnfp4nl)*

**Comment by tomivirkki** [comment]
:lgtm:

---

Reviewed 4 of 6 files at r1, 2 of 2 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-notification/34#-:-L0iMqNcgeuw4goPCcDS:bnfp4nl)*

**Pull request merged**
