### PR TITLE
Add z-index 1000

### LINKED ISSUE #25: Fix default z-index
Any positioned element in the body with a z-index will end up above the notifications.

Add `z-index: 1000;` to the element styles

### PR DESCRIPTION
**Pull request by YuriyVaadin**
Fixes #25 

Add `z-index` style to `content` part, so notifications will be displayed on top of all other elements.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-notification/29)

### CODE REVIEW

**Comment by manolo** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-notification.html, line 37 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-notification/29#-L-WcMi_Br8Ilog0Z2aP:-L-WcMi_Br8Ilog0Z2aQ:b-mqseia) ([raw file](https://github.com/vaadin/vaadin-notification/blob/f257089d4172983dad88f9640ed0656c3e14ca0d/vaadin-notification.html#L37)):*
> ```HTML
>       [part="content"] {
>         position: fixed;
>         z-index: 1000;
> ```

Why this magic number?. Probably using the maximum allowed makes more sense

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-notification/29)*

**Comment by tomivirkki** [comment]
Why not the `:host` element? And should this be in `<vaadin-overlay>` repo (for all overlays)?

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-notification/29#-:-L-WbP2XqDggv9xBMj5Q:b-feznu1)*

**Comment by platosha** [comment]
> Why not the :host element?

Double this question. Have to double check that, but I assume this needs to be set on the host to guarantee that the notification overlay is above all other overlays.

>  should this be in <vaadin-overlay> repo (for all overlays)?

I would doubt that. The notification overlay is a special kind, it should always be above other overlays. Having the same `z-index` for all the overlays makes an issue here: the stacking order becomes DOM order-dependant.

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-notification/29#-:-L-Wh65xSrgRBNUHyWvL:b6mddea)*

**Comment by platosha** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[vaadin-notification.html, line 37 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-notification/29#-L-WcMi_Br8Ilog0Z2aP:-L-WifLSZ4MtMKEp80Zu:b-z68srz) ([raw file](https://github.com/vaadin/vaadin-notification/blob/f257089d4172983dad88f9640ed0656c3e14ca0d/vaadin-notification.html#L37)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

Why this magic number?. Probably using the maximum allowed makes more sense
</blockquote></details>

Doubt that. IMO using reasonlably high number is OK. `1000` is fine too.

We just have to make sure that this number is higher than what the other `<vaadin-overlay>`s use, and that’s it.

Actually, CSS specs do not define ranges of integer, so the actual max allowed number is kinda platform-dependant...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-notification/29)*

**Comment by YuriyVaadin** [comment]
> Why not the `:host` element? 

It's because overlays `host` doesn't have any `position` set. Its size `0x0`. The same is for `overlay` part. So I am applying it to the `content` part. (Tested on demo)

> And should this be in `<vaadin-overlay>` repo (for all overlays)?

I agree with Anton, it will cause an DOM order-dependancy issue and there is no need in that.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[vaadin-notification.html, line 37 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-notification/29#-L-WcMi_Br8Ilog0Z2aP:-L-Wk3vRxEWMg5TCk00e:bbkuo67) ([raw file](https://github.com/vaadin/vaadin-notification/blob/f257089d4172983dad88f9640ed0656c3e14ca0d/vaadin-notification.html#L37)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

Doubt that. IMO using reasonlably high number is OK. `1000` is fine too.

We just have to make sure that this number is higher than what the other `<vaadin-overlay>`s use, and that’s it.

Actually, CSS specs do not define ranges of integer, so the actual max allowed number is kinda platform-dependant...
</blockquote></details>

I get this number from the description of the issue.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-notification/29#-:-L-Wk8v6bXf52EbKirqS:b-x5ul0b)*

**Comment by tomivirkki** [comment]
> I would doubt that. The notification overlay is a special kind

I think all overlays suffer from the same issue (any element with z-index under body will be rendered over the overlay)

> It's because overlays host doesn't have any position set. Its size 0x0. The same is for overlay part. So I am applying it to the content part. (Tested on demo)

The size shouldn't matter. If we make it relative and add z-index it should work? If we only set it to content, the backdrop will not be affected. This is not a problem with notification since it doesn't use backdrop but the elements should be aligned.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-notification/29#-:-L-a9beLlpjdxPE3W-aZ:bojfkuq)*

**Comment by tomivirkki** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-notification/29#-:-L-kAO0UlmDpkxnuEuJU:bnfp4nl)*

**Pull request merged**
